import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";
import Card from "../components/Card";
import coffeeStoresData from "./data/coffee-stores.json";
import { fetchCoffeeStores } from "../lib/coffee-stores";

const inter = Inter({ subsets: ["latin"] });

// Staticprops
export async function getStaticProps(context) {
  
  const coffeeStores = await fetchCoffeeStores()
  
  return {
    props: {
      coffeeStores
    },
  };
}

export default function Home(props) {
  // console.log("props", props);
  const handleOnBannerbuttonClick = () => {};

  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner
          handleOnClick={handleOnBannerbuttonClick}
          buttonText="Viex stores nearby"
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            width={700}
            height={400}
            alt="hero-image"
          />
        </div>
        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((el) => {
                return (
                  <Card
                    key={el.fsq_id}
                    className={styles.card}
                    imgUrl={
                      el.imgUrl ||
                      "https://images.unsplash.com/photo-1498804103079-a6351b050096?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2468&q=80"
                    }
                    name={el.name}
                    href={`/coffee-store/${el.fsq_id}`}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </>
  );
}
